version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/data
    restart: always
    networks:
      - fastapi_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - fastapi_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/silkmind.com/fullchain.pem:/etc/letsencrypt/live/silkmind.com/fullchain.pem:ro
      - /etc/letsencrypt/live/silkmind.com/privkey.pem:/etc/letsencrypt/live/silkmind.com/privkey.pem:ro
    depends_on:
      - frontend
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge